version: '3.8'

services:
  server:
    container_name: ppt_generator_server
    build: 
      context: server/
      dockerfile: llm.Dockerfile
    environment:
      - GPT_TOKEN=${GPT_TOKEN}
      - GCS_DEVELOPER_KEY=${GCS_DEVELOPER_KEY}
      - GCS_CX=${GCS_CX}
    ports:
      - 8501:8501
    depends_on:
      - ollama
    networks:
      - ppt-docker-net

  ollama:
    volumes:
      - ./ollama:/root/.ollama
    container_name: ollama
    pull_policy: always
    tty: true
    restart: unless-stopped
    image: ollama/ollama:latest
    ports:
      - 11434:11434
    networks:
      - ppt-docker-net
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]



networks:
  ppt-docker-net:
    external: false
